services:
  - type: web
    name: karthikragula
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: ASK_MY_CHANNEL_URL
        sync: false
      - key: ASK_MY_CHANNEL_HANDLE
        sync: false
